//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SurveyQuestionaire
{
    using System;
    using System.Collections.Generic;
    
    public partial class Respons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Respons()
        {
            this.Commentsses = new HashSet<Commentss>();
        }
    
        public int ResponseID { get; set; }
        public string Response { get; set; }
        public int QuestionID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commentss> Commentsses { get; set; }
        public virtual Question Question { get; set; }
    }
}
